/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alpha.view;

import com.alpha.config.Context;
import com.alpha.model.OrderDetails;
import com.alpha.model.Orders;
import com.alpha.service.custom.OrderService;
import com.alpha.utils.Validation;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.joda.time.LocalDate;
import org.springframework.context.support.AbstractApplicationContext;

/**
 *
 * @author Harindu.sul
 */
public class ViewAllOrders extends javax.swing.JFrame {

    private AbstractApplicationContext context;
    private DefaultTableCellRenderer centerRenderer;

    public ViewAllOrders() {
        initComponents();
        this.context = Context.getInstance();
        this.centerRenderer = new DefaultTableCellRenderer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        startDateTxt = new javax.swing.JFormattedTextField();
        endDateTxt = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_load = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        betweenTwoDaysTransactionTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderDetailsTable = new javax.swing.JTable();
        btn_load1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        startDateTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        endDateTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Start Date");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("End Date");

        btn_load.setBackground(new java.awt.Color(51, 51, 51));
        btn_load.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_load.setForeground(new java.awt.Color(255, 255, 255));
        btn_load.setText("Load");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });
        btn_load.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_loadKeyPressed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        betweenTwoDaysTransactionTable.setAutoCreateRowSorter(true);
        betweenTwoDaysTransactionTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        betweenTwoDaysTransactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Time", "Order ID", "Discount", "Total", "Sub Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        betweenTwoDaysTransactionTable.setGridColor(new java.awt.Color(255, 255, 255));
        betweenTwoDaysTransactionTable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        betweenTwoDaysTransactionTable.setRowHeight(28);
        betweenTwoDaysTransactionTable.setSelectionBackground(new java.awt.Color(153, 153, 153));
        betweenTwoDaysTransactionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                betweenTwoDaysTransactionTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(betweenTwoDaysTransactionTable);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        orderDetailsTable.setAutoCreateRowSorter(true);
        orderDetailsTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order Details ID", "Description", "Com Dis", "Store Dis", "Pack Size", "Order Qty", "Unit Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderDetailsTable.setGridColor(new java.awt.Color(255, 255, 255));
        orderDetailsTable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        orderDetailsTable.setRowHeight(28);
        orderDetailsTable.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setViewportView(orderDetailsTable);

        btn_load1.setBackground(new java.awt.Color(51, 51, 51));
        btn_load1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_load1.setForeground(new java.awt.Color(255, 255, 255));
        btn_load1.setText("Check Last Orders 500");
        btn_load1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_load1ActionPerformed(evt);
            }
        });
        btn_load1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_load1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(endDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_load1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(endDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(btn_load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_load1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        getTransactions();
    }//GEN-LAST:event_btn_loadActionPerformed

    private void btn_loadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_loadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTransactions();
        }
    }//GEN-LAST:event_btn_loadKeyPressed

    private void betweenTwoDaysTransactionTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_betweenTwoDaysTransactionTableMousePressed
        setOrderDetails();
    }//GEN-LAST:event_betweenTwoDaysTransactionTableMousePressed

    private void btn_load1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_load1ActionPerformed
        setLast500();
    }//GEN-LAST:event_btn_load1ActionPerformed

    private void btn_load1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_load1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_load1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable betweenTwoDaysTransactionTable;
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_load1;
    private javax.swing.JFormattedTextField endDateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderDetailsTable;
    private javax.swing.JFormattedTextField startDateTxt;
    // End of variables declaration//GEN-END:variables

    private void getTransactions() {
        String text = startDateTxt.getText();
        String text1 = endDateTxt.getText();
        boolean v1 = Validation.validateEmptyTextFeald(text);
        boolean v2 = Validation.validateEmptyTextFeald(text1);
        if (!v1 && !v2) {
            DefaultTableModel m = (DefaultTableModel) betweenTwoDaysTransactionTable.getModel();
            int rowCount = m.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                m.removeRow(i);
            }
            try {
                LocalDate date1 = new LocalDate(text);
                LocalDate date2 = new LocalDate(text1);
                OrderService orderService = (OrderService) context.getBean("OrderService");
                List<Orders> all = orderService.getBetweenTodaysTransaction(date1, date2);
                if (all != null) {
                    for (Orders o : all) {
                        LocalDate date = o.getDate();
                        String dd = date.toString();
                        String time = o.getTime();
                        int id = o.getId();
                        double discounts = o.getDiscounts();
                        double total = o.getTotal();
                        double subTot = o.getSubTot();
                        m.addRow(new Object[]{
                            dd,
                            time,
                            id + "",
                            discounts + "0",
                            total + "0",
                            subTot + "0"
                        });
                    }

                    betweenTwoDaysTransactionTable.setModel(m);
                    centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                    betweenTwoDaysTransactionTable.setDefaultRenderer(String.class, centerRenderer);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "please Input dates");
        }
    }

    private void setOrderDetails() {
        int selectedRow = betweenTwoDaysTransactionTable.getSelectedRow();
        if (selectedRow > -1) {
            OrderService orderService = (OrderService) context.getBean("OrderService");
            DefaultTableModel m = (DefaultTableModel) betweenTwoDaysTransactionTable.getModel();
            DefaultTableModel mm = (DefaultTableModel) orderDetailsTable.getModel();
            int rowCount = mm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                mm.removeRow(i);
            }
            Object valueAt = m.getValueAt(selectedRow, 2);
            String stringOrderID = valueAt.toString();
            try {
                List<OrderDetails> all = orderService.getOrderDetailsByOrderId(Integer.parseInt(stringOrderID));
                if (all != null) {
                    for (OrderDetails o : all) {
                        mm.addRow(new Object[]{
                            o.getId() + "",
                            o.getDescription(),
                            o.getComDiscount() + "0",
                            o.getDiscount() + "0",
                            o.getPackSize(),
                            o.getOrderOTY() + "0",
                            o.getUnitPrice() + "0"
                        });
                    }
                    orderDetailsTable.setModel(mm);
                }
            } catch (Exception ex) {
                Logger.getLogger(ViewAllOrders.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void setLast500() {
        DefaultTableModel m = (DefaultTableModel) betweenTwoDaysTransactionTable.getModel();
        int rowCount = m.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            m.removeRow(i);
        }
        OrderService orderService = (OrderService) context.getBean("OrderService");
        try {
            List<Orders> all = orderService.getLast500_OrderDetails();
            if (all != null) {
                for (Orders o : all) {
                    LocalDate date = o.getDate();
                    String dd = date.toString();
                    String time = o.getTime();
                    int id = o.getId();
                    double discounts = o.getDiscounts();
                    double total = o.getTotal();
                    double subTot = o.getSubTot();
                    m.addRow(new Object[]{
                        dd,
                        time,
                        id + "",
                        discounts + "0",
                        total + "0",
                        subTot + "0"
                    });
                }

                betweenTwoDaysTransactionTable.setModel(m);
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                betweenTwoDaysTransactionTable.setDefaultRenderer(String.class, centerRenderer);
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewAllOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
